### ISSUE TITLE
Plagiarism Of Your Project By Matthew Toms-Zuberec

### ISSUE THREAD

**Issue by ihateplagiarism** [wobsoriano/covid3d#29]
A grade 12 high school student by the name of **Matthew Toms-Zuberec** in Calgary Alberta seems to have directly plagiarized and monetized your project at https://seethespread.com/. 

The local news has featured him in an article, where he claims ["the site took him three weeks to build"](https://globalnews.ca/news/6984389/coronavirus-calgary-student-3d-interactive-website/). A superficial viewing proved they are pretty much identical to your project - except that he added a donation page to himself. In addition, he has claimed [$200 in donations ](https://ko-fi.com/acmkan) and on his LinkedIn, claims he is a Schulich Scholar Recipient which is a prestigious $100,000 scholarship. This implies he may have claimed your project in order to falsely gain this scholarship. 

If he has a relationship with you that I am unaware of, please DM me and I will remove this immediately. This is not a definite proof - just an accusation. 

![image](https://user-images.githubusercontent.com/85803898/121785526-733f3100-cb77-11eb-8246-7da810b72bd5.png)

**Comment by ihateplagiarism** [comment]
Since this is an accusation, I should probably remove this until it is proved.

**Comment by wobsoriano** [comment]
Hello @real-acmkan, 

You should have kept the GNU license, as well as all of the requirements here:  https://opensource.stackexchange.com/a/4582

**Comment by real-acmkan** [comment]
@ihateplagiarism 

I am writing to respond to this accusation, which as noted is an unproven one, but still is something I take very seriously. Please be clear that I have never claimed the original source code was mine, and have always credited the original author @wobsoriano in my README file, and on my website, back when the code was hosted under a different username (https://github.com/sorxrob/covid-3d). This can be verified via the wayback machine and my commits. I have updated the links now to point to this repository so that this is clear. I do agree it was an oversight to not include the GNU license and have added it now.

As for the media coverage, I have no control over what pieces of a lengthy interview they decide to produce for coverage or the accuracy of any quotes attributed to me. The media portion where I mention it took me three weeks to build was about the rest of the site, and the other pages functionality. While I have no control over what they report or its accuracy, I can see how the coverage can be taken out of context. The donation page has always been on my portion of the site, https://seethespread.com/dashboard.html, where I chose to monetize that section I built and include the donation for my work. That was at the recommendation of my dad, and my only donors were my uncle and 1 family friend and 1 high school friend, just fyi. I did however use the images of the globe on my donation page and an inaccurate summary, which was an error. I would welcome the opportunity to talk with @wobsoriano to discuss.  

As for my scholarship, that was based on academic achievement, charity and volunteer work and a number of projects I worked on. 

This was not an instance of plagiarism, I have provided clarification above, and I request that you please remove these inaccurate postings about me immediately.
